### ISSUE TITLE
Notice: Undefined variable: content_after

### ISSUE THREAD

**Issue by tyrann0us** [webgilde/image-source-control#17]
`Notice: Undefined variable: content_after in path\to\plugins\image-source-control-isc\public\public.php on line 166` when using the shortcode `[isc_list]`.

Image list is missing completely.

WordPress v4.9.6 based on [Bedrock](https://roots.io/bedrock/) with Twenty SeventeenVersion v1.6
Image Source Control v1.9.5
PHP v7.1.12

**Comment by webzunft** [comment]
@tyrann0us thank you!

I just uploaded the fix to master. Would you mind testing it as well?

**Comment by tyrann0us** [comment]
LGTM.
Image list was missing because none of the attachment had credits saved. So not related to the PHP notice.
Closed as fixed in e9aa60d4b9b8181e65fda492846f264380397c3b.

**Comment by webzunft** [comment]
Thanks!
