### ISSUE TITLE
Images haven't been indexed yet.

### ISSUE THREAD

**Issue by AdityaNayak** [webgilde/image-source-control#2]
I get this error 
![image](https://cloud.githubusercontent.com/assets/1292443/22407740/63b01f5c-e692-11e6-9899-128d60ab1102.png)

And on top it says
Missing Sources
No empty sources found!

**Comment by webzunft** [comment]
Thanks. I guess you have images with soures set up correctly?

**Comment by AdityaNayak** [comment]
I think so.

I'll be able to confirm with complete confidence if you can point me to
what should the ideal config be.

**Comment by webzunft** [comment]
Sure. You can follow the installation instructions and guidelines from https://webgilde.com/en/image-source-control/image-source-control-manual/.

**Comment by webzunft** [comment]
@AdityaNayak is this still an open problem?
