### ISSUE TITLE
Shortcodes do not display anything

### ISSUE THREAD

**Issue by jscheytt** [webgilde/image-source-control#3]
I have added sources, URLs or checked the "It's mine" checkbox on several images that are used on published pages.

Whenever I insert one of the shortcodes [isc_list] or [isc_list_all] into a page, the shortcode is executed (the literal shortcode is not showing anymore), but no content is generated on the page. How can I make the sources display?

(If that has any influence: The site uses Visual Composer elements.)

**Comment by webzunft** [comment]
Hi @jscheytt, thanks for your report. How do you use VC elements with this shortcode? Could you please try without using VC on a site?

**Comment by jscheytt** [comment]
Hey @webzunft, my fault: I did not use the `included="all"` inside the shortcode - it works now!
