### ISSUE TITLE
Some Links have no rel=""

### ISSUE THREAD

**Issue by Kipperlenny** [webgilde/image-source-control#33]
See Line https://github.com/webgilde/image-source-control/blob/v1.10/public/public.php#L108

my link tags have no rel attribute (perhaps because it's an ACF field, perhaps it's because we have a lightbox plugin as well). 

this should still be matched correctly. At the moment I changed this line to:

`$pattern = '#(<[^>]*class="[^"]*(alignleft|alignright|alignnone|aligncenter).*)?((<a [^>]*(href="([^"]*)"[^>]*)>)? *(<img [^>]*[^>]*src="(.+)".*\/?>).*(</a>)??[^<]*).*(<\/figure.*>)?#isU';`

and I have set $id to false in line 121.

With this change, it can find Links withouth rel attribute as well.

**Comment by webzunft** [comment]
I am not sure what you mean. If I link an image to an external website, the URL does not get a `rel` attribute with or without ISC enabled. How can I best reproduce this?

**Comment by Kipperlenny** [comment]
Link it to the media file - not to an external page.

`<a href="https://image.jpg"><img class="aligncenter wp-image-19324 size-medium" src="https://image-300x200.jpg" alt="" width="300" height="200" /></a>`

![image](https://user-images.githubusercontent.com/563328/67116103-0af04e80-f1e0-11e9-9e65-9f966d7588d2.png)

**Comment by webzunft** [comment]
Thanks. There is no `rel` attribute with or without ISC when I link to the media file either.
When I understand your first report correct then you are reporting that ISC cannot find links without the `rel` attribute, but as far as I see, this is the default behavior and it works fine. Am I missing something?

**Comment by Kipperlenny** [comment]
In our WordPress, ISC found them - and destroyed them :-D
After ISC filter, the html source looked like this:

`<div from isc with source></div><img class="aligncenter wp-image-19324 size-medium" src="https://image-300x200.jpg" alt="" width="300" height="200" /></a>`

The starting <a> Tag was missing.

Thats why I changed the regex to `<a [^>]*(href="`

**Comment by webzunft** [comment]
I imported the HTML code to my local installation and it worked perfectly. The `a` tag was also preserved.
