### ISSUE TITLE
Compatibility Elementor

### ISSUE THREAD

**Issue by creating** [webgilde/image-source-control#72]
Hey, is there any Option to get a compatibility to Elementor page builder?
For now the Plugin doesn't recognize any Image which is coming from Elementor so far.
Or is there any Option for a function.php or something similar to get the ISC-Information out of Elementors Image-Galleries, Background-Images or the simple Image-Element?

**Comment by webzunft** [comment]
Thanks for creating this issue.

Can you say if the images are also hosted in the WordPress media library or does Elementor have their own, separate folder for that? In that case, ISC is indeed currently not compatible and I would need to take a closer look.

**Comment by creating** [comment]
Hi @webzunft, wäre deutsch ok?
Hier der Link zu einer Entwicklungs-Umgebung. In der nutzen wir von Elementor die Shortcode-Template-Funktion. Bei den oberen Beiträgen (die per Beitragsbild ausgegeben werden) funktioniert der Shortcode noch. Aber für den unteren Inhalt, der das Elementor-Gallery-Element nutzt, oder bei den Einträgen, wenn das Bild als Hintergrund definiert wird, funktioniert es nicht mehr.

Link https://h4u.nodecrew.de/location/germany/nordrhein-westfalen/

**Comment by webzunft** [comment]
Natürlich gerne auch auf deutsch. Sind die Bilder für die du die Quellen vermisst under _Medien > Medienübersicht_ zu finden?

**Comment by creating** [comment]
Ja, alle da und Copyright-Hinweise sind auch eingetragen. Ich vermute, dass das Plugin die Template-Bausteine nicht mit bekommt.

**Comment by webzunft** [comment]
Ich habe mir mal den Quellcode angeschaut und in der Tat findet ISC die Bilder nicht, weil sie nicht als Bilder eingebunden sind. Im Code sind das sogar nur Attribute die dann erst später zu Hintergrundbildern umgeschrieben werden.

Beispiel

`<div class="e-gallery-image elementor-gallery-item__image" data-thumbnail="https://h4u.nodecrew.de/wp-content/uploads/2020/06/WP_20170616_13_05_50_Pro-300x169.jpg" data-width="300" data-height="169" alt="Externsteine im Teutoburger Wald" ></div>`

Um das zu lösen, und zwar nicht nur speziell für Elementor, müsste ich den gesamten Quellcode nach URLs durchsuchen die wie Bilder aussehen. Das ist technisch möglich, kann aber dazu führen, dass (auf anderen Webseiten) zu viele Bilder gefunden werden. Ich könnte mal eine Lösung entwerfen, wenn ihr bereit seid diese zu testen.

**Comment by creating** [comment]
Das wäre super. Würden wir gerne testen wollen.

**Comment by webzunft** [comment]
@creating wenn ihr mutig seid, dann habe ich schon etwas zum Testen. Bitte melde dich mal über http://webgilde.com/de/kontakt

**Comment by creating** [comment]
Moin, sieht super aus. Das einzige ist, ob man Ausnahmen mit geben kann. Das Logo wird aktuell noch mit ausgeworfen.

https://h4u.nodecrew.de/location/germany/baden-wuerttemberg/

**Comment by webzunft** [comment]
Danke für das Feedback. Gib einfach keine Quelle für das Logo an, dann sollte es auch ignoriert werden.

**Comment by creating** [comment]
Macht Sinn. :D

**Comment by creating** [comment]
Hi, sorry aber, wenn ich keine Quelle angebe, kommt das Logo trotzdem, vermutlich weil es immer beschnitten wird, auch wenn ich es nicht beschnitten hab.

**Comment by webzunft** [comment]
@creating meinst du `cropped-h4ylogo.jpg: holiday4you`? Das `holiday4you` sollte die hinterlegte Quelle sein.

**Comment by creating** [comment]
Klar, allerdings hab ich beim Ursprungs-Logo angegeben, dass es mein Bild ist. Sollte also gar nicht erscheinen.

**Comment by webzunft** [comment]
Da gab es einen Bug den ich gefixt haben sollte. Am besten erstmal die Checkbox und Quelle rausnehmen.
